name: notebook
channels:
  - conda-forge
dependencies:
  - cftime
  - cmaps
  - fsspec
  - intake-esm
  - nc-time-axis
  - netcdf4
  - pangeo-notebook=2020.07.18
  - pip
  - s3fs
  - watermark
  - zarr
  - cartopy
